name: CI

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

env:
      URI_DEV: ${{vars.URI_DEV}}
      HIII: ${{secrets.NEW}}
      MyNEW: "HI HELLO NEW"

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo "AWS_CODE=$ {{ vars.URI_DEV }}" >> $GITHUB_ENV
          echo "${{ env.AWS_CODE }}"
          echo "s3://$URI_DEV/"
          echo "$HIII"
          echo "$MyNEW"

      - name: test var      
        run: |
          echo "AWS_PROD=${{ vars.URI_PROD }}" >> $GITHUB_ENV
          echo "$AWS_PROD"

      - name: Set Commit SHA and Image Tag
      
        run: |
         COMMIT_SHA=$(git rev-parse --short HEAD)
         IMAGE_TAG=${COMMIT_SHA}
     


      - name: test more
        run: | 
          echo "hello"
          echo "AWS_REGION=${{ vars.URI_PROD }}" >> $GITHUB_ENV
          echo "$AWS_REGION"
      
      - name: Set env
        run: |
          URI_DEV="NEW VALUE"
          HIII=${{vars.URI_DEV}}
          echo "$URI_DEV"
          echo "$HIII"
