name: CI

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

env:
      URI_DEV: ${{ env.URI_DEV }} 

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo "$URI_DEV"
