name: CI

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

env:
      URI_DEV: ${{vars.URI_DEV}}
      HIII: ${{secrets.NEW}}
      MyNEW: "HI HELLO NEW"

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo "s3://$URI_DEV/"
          echo "$HIII"
          echo "$MyNEW"
